project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  - source: /src/i18n/zh-CN/**/*.json
    translation: /src/i18n/%two_letters_code%/**/%original_file_name%
    type: json
